import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { Nav, Sidebar, StoreProvider } from '@/components';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Nav />

          <div className="flex flex-col md:flex-row pt-[79px]">
            <Sidebar />
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
